apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: site-vitrine-loutik
  namespace: site-internet
spec:
  entryPoints:
    - web
  routes:
    - match: host(`www.loutik.fr`)
      kind: Rule
      services:
        - name: site-vitrine-loutik
          port: 80