apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-admin-config
  namespace: site-internet
data:
  settings.yaml: |
    title: Admin | Launcher LoutikCLOUD
    favicon: https://raw.githubusercontent.com/firetoak/loutik-cloud_launcher-admin/main/assets/logo_loutik-health.png
    headerStyle: boxed
    hideVersion: true
    disableIndexing: true

  widgets.yaml: |
    - logo:
        icon: https://raw.githubusercontent.com/firetoak/loutik-cloud_launcher-admin/main/assets/logo_loutik-health.png
    - datetime:
        text_size: xl
        format:
          timeStyle: short
          hourCycle: h23
    - search:
        provider: duckduckgo
        target: _blank 

  services.yaml: |
    - Hyperviseur & Orchestrateur:
      - PVE Darlene:
          href: https://pve-darlene.loutik.fr
          siteMonitor: https://pve-darlene.loutik.fr
          icon: proxmox
      - PVE Gideon:
          href: https://pve-gideon.loutik.fr
          siteMonitor: https://pve-gideon.loutik.fr
          icon: proxmox
    - Réseau:
        - OPNsense:
            href: https://routeur.loutik.fr
            siteMonitor: https://routeur.loutik.fr
            icon: opnsense
        - Switch Zyxel:
            href: https://switch.loutik.fr
            siteMonitor: https://switch.loutik.fr
            icon: zyxel-networks
    - Services:
        - Grafana (Supervision):
            href: https://supervision.loutik.fr
            siteMonitor: https://supervision.loutik.fr
            icon: grafana
        - Authentik (SSO):
            href: https://sso.loutik.fr
            siteMonitor: https://sso.loutik.fr
            icon: authentik

  bookmarks.yaml: |
    - Sécurité:
        - Tailscale (VPN):
            - icon: tailscale-light
              href: https://login.tailscale.com/admin/machines
        - Crowdsec (WAF):
            - icon: crowdsec
              href: https://app.crowdsec.net/security-engines
    - Administration:
        - Documentation LoutikCLOUD:
            - icon: gitbook
              href: https://docs.loutik.fr/docs/intro/

  docker.yaml: |
    # Configuration docker vide
  
  kubernetes.yaml: |
    # Configuration kubernetes vide
  
  custom.css: |
    /* Styles personnalisés */
  
  custom.js: |
    // Scripts personnalisés