apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: site-internet
data:
  settings.yaml: |
    title: Launcher LoutikCLOUD
    favicon: https://raw.githubusercontent.com/firetoak/medias/main/logo/logo_loutikhealth.png
    headerStyle: boxed
    hideVersion: true
    disableIndexing: true

  widgets.yaml: |
    - logo:
        icon: https://raw.githubusercontent.com/firetoak/medias/main/logo/logo_loutikhealth.png
    - datetime:
        text_size: xl
        format:
          timeStyle: short
          hourCycle: h23
    - search:
        provider: duckduckgo
        target: _blank 

  services.yaml: |
    - Site internet :
      - Documentation:
          href: https://docs.loutik.fr
          siteMonitor: https://docs.loutik.fr
          icon: proxmox
      - Site vitrine:
          href: https://www.loutik.fr
          siteMonitor: https://www.loutik.fr
          icon: proxmox
      - Portfolio:
          href: https://louis.loutik.fr
          siteMonitor: https://louis.loutik.fr
          icon: proxmox

  bookmarks.yaml: |
    - Sécurité:
        - Tailscale (VPN):
            - icon: tailscale-light
              href: https://login.tailscale.com/admin/machines
        - Crowdsec (WAF):
            - icon: crowdsec
              href: https://app.crowdsec.net/security-engines
    - Administration:
        - Documentation LoutikCLOUD:
            - icon: gitbook
              href: https://docs.loutik.fr/docs/intro/

  docker.yaml: |
    # Configuration docker vide
  
  kubernetes.yaml: |
    # Configuration kubernetes vide
  
  custom.css: |
    /* Styles personnalisés */
  
  custom.js: |
    // Scripts personnalisés