apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage-launcher-admin
  namespace: site-internet
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`launcher.loutik.lab`)
      kind: Rule
      services:
        - name: homepage-launcher
          port: 80