apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - namespace.yaml
  - ingress.yaml

configMapGenerator:
  - name: homepage-admin-config
    namespace: site-internet
    files:
      - settings.yaml
      - widgets.yaml
      - services.yaml
      - bookmarks.yaml
      - docker.yaml
      - kubernetes.yaml
      - custom.css
      - custom.js