---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Site internet :
    - Documentation:
        href: https://docs.loutik.fr
        siteMonitor: https://docs.loutik.fr
        icon: https://docs.loutik.fr
    - Site vitrine:
        href: https://www.loutik.fr
        siteMonitor: https://www.loutik.fr
        icon: https://www.loutik.fr
    - Portfolio:
        href: https://louis.loutik.fr
        siteMonitor: https://louis.loutik.fr
        icon: https://louis.loutik.fr