apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage-admin
  namespace: site-internet
  labels:
    app: homepage-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage-admin
  template:
    metadata:
      labels:
        app: homepage-admin
    spec:
      containers:
      - name: homepage-admin
        image: ghcr.io/gethomepage/homepage:latest
        env:
          - name: HOMEPAGE_ALLOWED_HOSTS
            value: launcher-admin.loutik.fr
        resources:
          requests:
            memory: "60Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - name: http
            containerPort: 3000
            protocol: TCP
        volumeMounts:
          - mountPath: /app/config/custom.js
            name: homepage-admin-config
            subPath: custom.js
          - mountPath: /app/config/custom.css
            name: homepage-admin-config
            subPath: custom.css
          - mountPath: /app/config/bookmarks.yaml
            name: homepage-admin-config
            subPath: bookmarks.yaml
          - mountPath: /app/config/docker.yaml
            name: homepage-admin-config
            subPath: docker.yaml
          - mountPath: /app/config/kubernetes.yaml
            name: homepage-admin-config
            subPath: kubernetes.yaml
          - mountPath: /app/config/services.yaml
            name: homepage-admin-config
            subPath: services.yaml
          - mountPath: /app/config/settings.yaml
            name: homepage-admin-config
            subPath: settings.yaml
          - mountPath: /app/config/widgets.yaml
            name: homepage-admin-config
            subPath: widgets.yaml
          - mountPath: /app/config/logs
            name: logs
      volumes:
      - name: homepage-admin-config
        configMap:
          name: homepage-admin-config
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: homepage-admin
  namespace: site-internet
spec:
  type: ClusterIP
  selector:
    app: homepage-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http