apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage-admin
  namespace: site-internet
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`launcher-admin.loutik.fr`)
      kind: Rule
      middlewares:
        - name: authentik-forwardauth
      services:
        - name: homepage-admin
          port: 80